name: Third Pipeline

on:
  push :
      branches:
        - master
permissions:
  actions: write 
  contents: read

jobs:
  call-other-pipelines:
    uses: ./.github/workflows/firstpipeline.yml
    with: {}

  call-second-pipelines:
    uses: ./.github/workflows/secondpipeline.yml
    with: {}
  process-results:
    needs: call-other-pipelines
    runs-on: ubuntu-latest
    steps:
      - name: Use Variables from First and Second Pipelines
        env:
          FIRST_VAR: ${{ needs.call-other-pipelines.outputs.VAR_FROM_FIRST_PIPELINE }}
          SECOND_VAR: ${{ needs.call-other-pipelines.outputs.VAR_FROM_SECOND_PIPELINE }}
        run:
           'echo "First Pipeline Output: $FIRST_VAR, Second Pipeline Output: $SECOND_VAR"'
